[project]
name = "galaxy-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bioblend>=1.5.0",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"
select = ["E", "F", "W", "I", "N", "B", "UP", "A", "C4", "SIM", "PT"]
